apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ct6t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-ct6t@sha256:8ef35fd24a875f5192b9d5e6357ea56810a1e1e4f0c42e13c77fd422ec060c25
        name: my-nodejs
        resources: {}
status: {}
